<?php
require 'Functions-Classes.php';
$p1 = new Person("Alice", 25,"alice@example.com");
echo $p1->getName();
echo '<br>';
echo $p1 ->intro();
echo '<br>';
$s1 = new studente("Bob", 15,"bob@example.com","IIS ViolaMarchesini");
echo $s1->intro();
echo '<br>';
echo '<br>';
echo $s1->presentation();
echo '<br>';
echo $s1->toDo();
echo '<br>';
echo '<br>';
echo studente::class.'<br>';
echo '<br>';
$t1 = new Teacher("emiliano","spiller");
$t2 = new Teacher("enrico","dall'ara");
$t3 = new Teacher("giacomo","mazzulo");
echo Teacher::getRegister();